### PR TITLE
feat: migrate to null safety

### PR DESCRIPTION
**Pull request by chimon2000**
The purpose of this pull request is to migrate the package to null safety.

### CODE REVIEW

**Comment by nuc134r** [comment]
@chimon2000 thanks for migrating my code!

Are you doing random automated migrations? This package does not seem very popular :)

**Comment by chimon2000** [comment]
We depend on it for a project that I am currently working on 🙂

**Comment by alberto-sf** [comment]
Hello @nuc134r! May you please get the chance to merge this PR and bump the version at pub? 😄

**Comment by nuc134r** [comment]
> Hello @nuc134r! May you please get the chance to merge this PR and bump the version at pub? 😄 

God, this is so much pressure. I wanted to review and see for myself if it works as should but haven't got time for that this weekend.

@chimon2000 @alberto-sf 
Do y'all guarantee it compiles and works okay? Then bump the pubspec version as well. I will press merge button and when I get home I'll publish it to the pub.dev

Thanks

**Comment by alberto-sf** [comment]
Yes it's fine! It's been just a matter of replacing `@required` with `required` and adding some `!`. This is an easy job for the dart migration tool

**Comment by nuc134r** [comment]
I forgot about this PR and just migrated to null safety myself in v2.0.0, sorry.

I hope you just copied the code and migrated it as a part of your app and forgot about the issue. Thank you for your time and PR!

**Pull request closed without merging**
