### PR TITLE
Remove unneccessary null-aware operator ?.

### LINKED ISSUE #3: Unneccessary null-aware operator ?.
From https://pub.dev/packages/scroll_shadow_container/score

> WARNING: The receiver can't be null, so the null-aware operator '?.' is unnecessary.
> `lib/scroll_shadow_container.dart:182:9`

```
    ╷
182 │         ?.addPostFrameCallback((_) => _updateShadowsVisibility());
    │         ^^
    ╵
```

Would be nice to fix it.

### PR DESCRIPTION
**Pull request by timukasr**
Fixes #3

### CODE REVIEW

**Comment by nuc134r** [comment]
@timukasr thanks for your contribution. After the fix it still gives me a (different) lint warning locally, maybe because of my environment. I'll take a deeper look later

**Comment by nuc134r** [comment]
@timukasr 

IDE (and `flutter analyze`) gives me following error:

image

It's either compiles and and successfully gets published with the following warning on pub.dev (initial code):
>The receiver can't be null, so the null-aware operator '?.' is unnecessary.

Either it does not compile with following error (after fix):
>The method 'addPostFrameCallback' can't be unconditionally invoked because the receiver can be 'null'

Maybe I don't understand Dart's null safety enough yet. But for now it works although the package score is lowered.

**Comment by nuc134r** [comment]
I'd like to revert this fix until someone (perhaps future me) figures it out. 

Two messages contradict each other but one is a warning and other is a error so I went with warning.

**Comment by timukasr** [comment]
It seems that with Flutter 3 `WidgetBinding.instance` instance was changed to be non-nullable. I'm using Flutter 3, so it was fine for me. With Flutter 2.x, it indeed gives error. One option to fix warning and support Flutter 2:
```
/// This allows a value of type T or T?
/// to be treated as a value of type T?.
T? _ambiguate<T>(T? value) => value;

_ambiguate(WidgetsBinding.instance)?.addPostFrameCallback((_) => _updateShadowsVisibility());
```

**Comment by nuc134r** [comment]
@timukasr I followed your suggestion and published 2.1.1+1 version on pub.dev. Can you verify it still works in an actual app? :)

**Comment by timukasr** [comment]
Yes, it works in app and warning is gone. Thank you.

**Pull request merged**
